/**
 * DO NOT EDIT THIS FILE (truffle.js)
 * Use config/ for configuration for consistency
 */
const config = require('config');

module.exports = {
  build: 'echo', // overwrite default bundling. All we need is compiled contracts
  mocha: {
    useColors: true,
  },
  rpc: config.rpc,
};
